[package]
name            = "coaster-blas"
description     = "Coaster library for full BLAS support"
version         = "0.2.1"
authors         = ["Bernhard Schuster <bernhard@ahoi.io>",
                   "Michael Hirn <mj@autumnai.com>",
                   "Maximilian Goisser <max@autumnai.com>"]

repository      = "https://github.com/spearow/coaster-blas"
homepage        = "https://spearow.io/projects/coaster-blas"
documentation   = "https://spearow.github.com/coaster-blas"
readme          = "README.md"

keywords        = ["blas", "coaster", "computation", "hpc", "plugin"]
license         = "MIT OR Apache-2.0"

[dependencies]
coaster = { version = "0.1", default-features = false }
lazy_static = "1"

# native
rblas = { version = "0.0", optional = true }

# cuda
rcublas = { version = "0.2",  optional = true }

clippy = { version = "0.0.302", optional = true }

[dev-dependencies]

rand = "0.6"

[features]
default = ["native", "cuda"]
native = ["coaster/native", "rblas"]
cuda = ["coaster/cuda", "rcublas"]
opencl = ["coaster/opencl"]

travis = ["native"]
dev = []
lint = ["clippy"]
