[package]
name            = "collenchyma-blas"
description     = "Collenchyma library for full BLAS support"
version         = "0.2.0"
authors         = ["Michael Hirn <mj@autumnai.com>",
                   "Maximilian Goisser <max@autumnai.com>"]

repository      = "https://github.com/ratpoison-io/collenchyma-blas"
homepage        = "https://ratpoison.io/collenchyma-blas"
documentation   = "https://autumnai.github.io/collenchyma-blas"
readme          = "README.md"

keywords        = ["blas", "collenchyma", "computation", "hpc", "plugin"]
license         = "MIT OR Apache-2.0"

[dependencies]
collenchyma = { path = "../collenchyma", default-features = false }
lazy_static = "0.1"

# native
rblas = { version = "0.0.11", optional = true }

# cuda
cublas = { git = "https://github.com/alexandermorozov/rust-cublas", optional = true }

clippy = { version = "0.0.27", optional = true }

[dev-dependencies]

rand = "0.3"

[features]
default = ["native", "cuda", "opencl"]
native = ["collenchyma/native", "rblas"]
cuda = ["collenchyma/cuda", "cublas"]
opencl = ["collenchyma/opencl"]

travis = ["native"]
dev = []
lint = ["clippy"]
