[package]
name            = "collenchyma-nn"
description     = "Collenchyma plugin for full Neural Network algorithm support"
version         = "0.0.1"
authors         = ["MichaelHirn <michael.hirn@storeness.de>"]

repository      = "https://github.com/autumnai/collenchyma-nn"
homepage        = "https://github.com/autumnai/collenchyma-nn"
documentation   = "https://autumnai.github.io/collenchyma-nn"
readme          = "README.md"

keywords        = ["neural-network", "collenchyma", "computation", "hfc", "plugin"]
license         = "MIT"

[dependencies]
collenchyma = { path = "/home/hobofan/collenchyma" }
# cudnn = "0.1.3"
cudnn = { git = "https://github.com/autumnai/rust-cudnn.git", rev = "6436d44" }
libc = "0.2"
lazy_static = "0.1"
clippy = { version = "0.0.27", optional = true }

[features]
dev = []
travis = []
lint = ["clippy"]
