[package]
name          = "coaster"
description   = "high-performance computation on any hardware"
version       = "0.1.0"
authors       = ["Bernhard Schsuter <bernhard@ratpoison.io>",
		 "Michael Hirn <mj@autumnai.com>",
                 "Maximilian Goisser <max@autumnai.com>"]

repository    = "https://github.com/ratpoison-io/coaster"
homepage      = "https://ratpoison.io/coaster"
documentation = "http://ratpoison.io/projects/coaster"
readme        = "README.md"

keywords      = ["backend", "computation", "opencl", "cuda", "hpc"]
license       = "MIT OR Apache-2.0"

[dependencies]
libc = "0.2"
bitflags = "0.3"
enum_primitive = "0.1.0"
byteorder = "0.4"
num = "0.1"
lazy_static = "0.1.15"

clippy = { version = "0.0.27", optional = true }
compiletest_rs = { version = "0.1", optional = true }

[dev-dependencies]
rand = "0.3"

[features]
default = ["native", "cuda", "opencl"]
native = []
cuda = []
opencl = []

unstable_alloc = [] # faster but unstable memory allocation on native machines

dev = []
unstable = ["compiletest_rs"] # for travis-cargo
travis = ["native"]
lint = ["clippy"]

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
