[package]
name = "leaf-examples"
description = "Examples for the Machine Learning Framework 'Leaf'"
version = "0.1.0"
authors = ["Michael Hirn <mj@autumnai.com>",
           "Maximilian Goisser <max@autumnai.com>"]

[dependencies]
csv = "0.14"
# cuticula = "0.1.4"
collenchyma = "0.0.8"
# leaf = { git = "https://github.com/autumnai/leaf.git" }
leaf = { git = "https://github.com/autumnai/leaf.git", rev = "38d5f48a5e8a875879661f7a792c9eab25295b65" }
collenchyma-blas = "0.2.0"
hyper = "0.6"

# CLI tooling
docopt = "0.6.75"
rustc-serialize = "0.3"

clippy = { version = "0.0.23", optional = true }

[profile.dev]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 2
